//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensifyApp.DataBase
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text;
    
    
    public partial class ExpenseTable
    {
        
        private int _sNo;
        
        [Key()]
        public int SNo
        {
            get
            {
                return this._sNo;
            }
            set
            {
                this._sNo = value;
            }
        }
        
        private string _category;
        
        public string Category
        {
            get
            {
                return this._category;
            }
            set
            {
                this._category = value;
            }
        }
        
        private string _subCategory;
        
        public string SubCategory
        {
            get
            {
                return this._subCategory;
            }
            set
            {
                this._subCategory = value;
            }
        }
        
        private string _payMode;
        
        public string PayMode
        {
            get
            {
                return this._payMode;
            }
            set
            {
                this._payMode = value;
            }
        }
        
        private System.DateTime _date;
        
        public System.DateTime Date
        {
            get
            {
                return this._date;
            }
            set
            {
                this._date = value;
            }
        }
        
        private int _expenses;
        
        public int Expenses
        {
            get
            {
                return this._expenses;
            }
            set
            {
                this._expenses = value;
            }
        }
        
        public static void CopyObject(ExpenseTable srcObject, ExpenseTable destObject, bool copyPrimaryKeyValue = true)
        {
            if (copyPrimaryKeyValue)
            {
                destObject.SNo = srcObject.SNo;
            }
            destObject.Category = srcObject.Category;
            destObject.SubCategory = srcObject.SubCategory;
            destObject.PayMode = srcObject.PayMode;
            destObject.Date = srcObject.Date;
            destObject.Expenses = srcObject.Expenses;
        }
        
        public virtual ExpenseTable CloneObject()
        {
            ExpenseTable srcObject = new ExpenseTable();
            srcObject.SNo = this.SNo;
            srcObject.Category = this.Category;
            srcObject.SubCategory = this.SubCategory;
            srcObject.PayMode = this.PayMode;
            srcObject.Date = this.Date;
            srcObject.Expenses = this.Expenses;
            return srcObject;
        }
    }
}
